# Generated by Django 4.2.11 on 2025-09-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rendezvous'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='contact_client',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='nom_client',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='titre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
